### ISSUE TITLE
AppEngine Support

### ISSUE THREAD

**Issue by Trupal00p** [yeoman/generator-polymer#205]
It would be really awesome if this generator supported AppEngine out of the box.  I would submit a pull request with how I did it below but I'm pretty new to the yeoman/gulp workflow so anything I write will probably be a mess.

Here's how I got it working manually:
1. Install generator-appengine
2. Install generator-polymer (this project)
3. cd to project folder
4. "Yo polymer"
5. cd into app folder
6. Yo appengine
7. Update app.yaml file to read:

```yaml
application: polymer-test
version: default
runtime: python27
threadsafe: yes
api_version: 1

handlers:

 - url: /
   static_files: index.html
   upload: index.html

 - url: /bower_components/
   static_dir: ../bower_components

 - url: /elements/
   static_dir: elements

 - url: /images/
   static_dir: images

 - url: /scripts/
   static_dir: scripts

 - url: /styles/
   static_dir: styles

 - url: /.*
   static_files: 404.html
   upload: 404.html
```

Then update the gulp.js file to use gulp-replace to fix the bower_components path in app.yaml when the copy task is run:

```javascript
  var app = gulp.src([
    'app/*',
    '!app/test',
    '!app/precache.json'
  ], {
    dot: true
  })
  .pipe(greplace('static_dir: ../bower_components','static_dir: bower_components'))
  .pipe(gulp.dest('dist'));
```

I used gulp-run to get the dev server started with the serve task and switched browsersync to use proxy mode:

(had to use a batch file to launch the dev server since gulp-run has issues with file paths that contain spaces on windows)

```javascript
var run = require('gulp-run');

// Watch Files For Changes & Reload
gulp.task('serve', ['styles', 'elements', 'images'], function () {
  run('launch_gae_dev_server.bat').exec();
  browserSync({
    notify: false,
    snippetOptions: {
      rule: {
        match: '<span id="browser-sync-binding"></span>',
        fn: function (snippet) {
          return snippet;
        }
      }
    },
    // Run as an https by uncommenting 'https: true'
    // Note: this uses an unsigned certificate which on first access
    //       will present a certificate warning in the browser.
    // https: true,
    // server: {
    //   baseDir: ['.tmp', 'app'],
    //   routes: {
    //     '/bower_components': 'bower_components'
    //   }
    // }
    proxy: 'localhost:9080'
  });
```
batch file:
```
python "[PATH TO APPENGINE]\dev_appserver.py" --port=9080 [app name]
```
